// apps/demo-react/src/Content/TokenActions/TokenActions.tsx
import Button from '@mui/material/Button'

import { useSigner } from '@usedapp/core'
import { Token, useToken } from '@erc-3643/react-usedapp'
import { useEffect, useState } from 'react'
import { BOB_WALLET, TOKEN_ADDRESS } from '../../constants'
import { StyledFieldRow, StyledTextField, StyledWalletExample } from './TokenActions.styles'

const TokenActions = () => {
  const signer = useSigner()
  const { getToken } = useToken(signer)
  const [token, setToken] = useState<Token | null>(null)
  const [freezeWallet, setFreezeWallet] = useState('')
  const [unfreezeWallet, setUnfreezeWallet] = useState('')

  useEffect(() => {
    if (!signer) {
      return
    }

    ;(async () => {
      setToken(await getToken(TOKEN_ADDRESS))
    })()
  }, [signer])

  const onPause = async () => {
    if (!token) {
      return
    }

    if (token.paused) {
      await token.run()
    } else {
      await token.pause()
    }

    setToken(await getToken(TOKEN_ADDRESS))
  }

  const onFreeze = () => {
    if (!freezeWallet || !token) {
      return
    }

    token.freeze(freezeWallet)
  }

  const onUnfreeze = () => {
    if (!unfreezeWallet || !token) {
      return
    }

    token.unfreeze(unfreezeWallet)
  }

  return (
    <>
      {' '}
      <h3>Token actions</h3>
      <div>
        Pause token:{' '}
        {token && (
          <Button variant='contained' color={token.paused ? 'success' : 'error'} onClick={onPause}>
            {token.paused ? 'Run' : 'Pause'}
          </Button>
        )}
      </div>
      <StyledFieldRow>
        <StyledTextField
          label='Wallet address to freeze'
          onChange={(e) => setFreezeWallet(e.target.value)}
        />
        <StyledWalletExample>ex. Bob wallet: {BOB_WALLET}</StyledWalletExample>
        <div>
          <Button variant='contained' color='secondary' onClick={onFreeze}>
            Freeze wallet
          </Button>
        </div>
      </StyledFieldRow>
      <StyledFieldRow>
        <StyledTextField
          label='Wallet address to unfreeze'
          onChange={(e) => setUnfreezeWallet(e.target.value)}
        />
        <StyledWalletExample>ex. Bob wallet: {BOB_WALLET}</StyledWalletExample>
        <div>
          <Button variant='contained' color='warning' onClick={onUnfreeze}>
            Unfreeze wallet
          </Button>
        </div>
      </StyledFieldRow>
    </>
  )
}

export default TokenActions

// project-root/apps/demo-vue/src/components/erc3643/TokenActions.vue
<script setup lang="ts">
import { useToken } from '@erc-3643/vue-usedapp'
import { ref, watch } from 'vue';
import { useEthers } from 'vue-dapp';
import { BOB_WALLET, TOKEN_ADDRESS } from '@/constants';

const { signer } = useEthers()

const token = ref<{ [key: string]: any }>({});


watch(signer, async (signer) => {
  if (signer) {
    token.value = await useToken(TOKEN_ADDRESS, signer);
  }
})

const addressFreeze = ref<string | null>(null);
const addressUnfreeze = ref<string | null>(null);

const walletFreeze = () => {
  console.log(addressFreeze.value)
  if (addressFreeze.value) {
    token.value.freeze(addressFreeze.value)
  }
}

const walletUnfreeze = () => {
  console.log(addressUnfreeze.value)
  if (addressUnfreeze.value) {
    token.value.unfreeze(addressUnfreeze.value)
  }
}
</script>
<template>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <q-card class="token-info">
      <q-card-section>
        <div class="text-h6">Token actions:</div>
      </q-card-section>
      <q-card-section>
        <p>
          Pause token:
          <q-btn v-if="token.paused" color="positive" @click="token.run" label="Run" dense />
          <q-btn v-else color="negative" @click="token.pause" label="Pause" dense />
        </p>
        <p>
          <q-input
            v-model="addressFreeze"
            label="Wallet address to unfreeze"
            :hint="`ex. Bob wallet ${BOB_WALLET}`"
            dense
          />
          <q-btn color="secondary" @click="walletFreeze" label="Freeze Wallet" dense />
        </p>
        <p>
          <q-input
            v-model="addressUnfreeze"
            label="Wallet address to freeze"
            :hint="`ex. Bob wallet ${BOB_WALLET}`"
            dense
          />
          <q-btn color="warning" @click="walletUnfreeze" label="Unfreeze Wallet" dense />
        </p>
      </q-card-section>
    </q-card>
  </div>
</template>
