// apps/demo-vue/src/components/erc3643/IdentityRegistryInfo.vue
<script setup lang="ts">
import { useIdentityRegistry, useToken } from '@erc-3643/vue-usedapp';
import { ref, watch } from 'vue';
import { useEthers } from 'vue-dapp';
import { TOKEN_ADDRESS } from '@/constants';

const { signer } = useEthers();

const investorCountry = ref(0);
const identityRegistryAddress = ref('');
watch(signer, async (signer) => {
  if (signer) {
    const { token } = await useToken(TOKEN_ADDRESS, signer);

    identityRegistryAddress.value = await token.identityRegistry();
    const identityRegistry = useIdentityRegistry(identityRegistryAddress.value, signer);

    investorCountry.value = await identityRegistry.getInvestorCountry(await signer.getAddress());
  }
})

</script>

<template>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <q-card class="identity-registry-info">
      <q-card-section>
        <div class="text-h6">Identity Registry info:</div>
      </q-card-section>
      <q-card-section>
        <p>Identity Registry: {{ identityRegistryAddress }}</p>
      </q-card-section>
      <q-card-section>
        <p>Investor Country: {{ investorCountry }}</p>
      </q-card-section>
    </q-card>
  </div>
</template>

// project-root/apps/demo-react/src/Content/IdentityRegistryInfo/IdentityRegistryInfo.tsx
import { TOKEN_ADDRESS } from '../../constants'
import { useSigner } from '@usedapp/core'
import { useEffect, useState } from 'react'
import { useIdentityRegistry, useToken } from '@erc-3643/react-usedapp'

const IdentityRegistryInfo = () => {
  const [investorCountry, setInvestorCountry] = useState('')
  const signer = useSigner()
  const token = useToken(TOKEN_ADDRESS, signer)
  const [identityRegistryAddress, setIdentityRegistryAddress] = useState('')
  const identityRegistry = useIdentityRegistry(identityRegistryAddress, signer)

  useEffect(() => {
    if (!token) {
      return
    }

    ;(async () => {
      setIdentityRegistryAddress(await token?.identityRegistry())
    })()
  }, [token])

  useEffect(() => {
    if (!identityRegistry || !signer) {
      return
    }

    ;(async () => {
      setInvestorCountry(await identityRegistry.getInvestorCountry(await signer.getAddress()))
    })()
  }, [identityRegistry, signer])

  return (
    <div>
      <h3>Identity Registry Info</h3>
      <div>Investor Country: {investorCountry}</div>
    </div>
  )
}

export default IdentityRegistryInfo
