// poc/vue-demo/@erc-3643/demo-vue/src/components/erc3643/TokenInfo.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useToken } from '@/composables'

const {
  balanceOf,
  decimals,
  name,
  owner,
  totalSupply,
  paused,
  frozenTokens,
  realBalanceOf,
  walletIsFrozen
} = useToken('0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE');

</script>

<template>
  <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
    <q-card class="token-info">
      <q-card-section>
        <div class="text-h6">Token info:</div>
      </q-card-section>
      <q-card-section>
        <p>Decimals: {{ decimals }}</p>
        <p>Name: {{ name }}</p>
        <p>Owner: {{ owner }}</p>
        <p>Total Supply: {{ totalSupply}}</p>
        <p>Balance Of: {{ balanceOf }}</p>
        <p>Frozen Tokens: {{ frozenTokens }}</p>
        <p>Real Balance Of: {{ realBalanceOf }}</p>
        <p>
          Wallet Is Frozen: {{ walletIsFrozen }}
        </p>
        <p>
          Token Is Paused: {{ paused }}
        </p>
      </q-card-section>
    </q-card>
  </div>
</template>

// project-root/apps/demo-react/src/Content/TokenInfo/TokenInfo.tsx
import { useToken } from '@erc-3643/react-usedapp'
import { TOKEN_ADDRESS } from '../../constants'
import { useSigner } from '@usedapp/core'
import { utils } from 'ethers'

const TokenInfo = () => {
  const { formatEther } = utils
  const signer = useSigner()
  const token = useToken(TOKEN_ADDRESS, signer)

  return (
    <div>
      <h3>Token info:</h3>
      <div>Decimals: {token?.decimals}</div>
      <div>Name: {token?.name ?? ''}</div>
      <div>Owner: {token?.owner}</div>
      <div>Total Supply: {formatEther(token?.totalSupply ?? 0)}</div>
      <div>Balance Of: {formatEther(token?.balanceOf ?? 0)}</div>
      <div>Frozen Tokens: {formatEther(token?.frozenTokens ?? 0)}</div>
      <div>Real Balance Of: {formatEther(token?.realBalanceOf ?? 0)}</div>
      <div>Wallet Is Frozen: {token?.walletIsFrozen ? 'Yes' : 'No'}</div>
      <div>Token Is Paused: {token?.paused ? 'Yes' : 'No'}</div>
    </div>
  )
}

export default TokenInfo
